In [5]:
import pandas as pd
from datetime import datetime, timedelta
from nba_api.stats.static import teams
from nba_api.stats.endpoints import teamgamelog

# Find team by abbreviation
team_abbreviation = 'LAL'  # Example: Los Angeles Lakers
nba_teams = teams.get_teams()
team_dict = [team for team in nba_teams if team['abbreviation'] == team_abbreviation][0]

# Fetch team game log data
team_id = team_dict['id']
current_season = '2023-24'  # Adjust the season accordingly
game_log = teamgamelog.TeamGameLog(team_id=team_id, season=current_season)

# Convert to DataFrame
game_log_df = game_log.get_data_frames()[0]

# Convert game date to datetime and filter for the last 10 days
game_log_df['GAME_DATE'] = pd.to_datetime(game_log_df['GAME_DATE'])
last_10_days = datetime.now() - timedelta(days=10)
filtered_games_df = game_log_df[game_log_df['GAME_DATE'] > last_10_days]

# Display the filtered DataFrame
filtered_games_df

,Team_ID,Game_ID,GAME_DATE,MATCHUP,WL,W,L,W_PCT,MIN,FGM,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS
0,1610612747,0022300869,2024-03-02,LAL vs. DEN,L,33,29,0.532,240,47,...,0.727,6,25,31,33,5,4,7,9,114
1,1610612747,0022300856,2024-02-29,LAL vs. WAS,W,33,28,0.541,265,53,...,0.833,7,38,45,30,6,6,11,16,134
2,1610612747,0022300848,2024-02-28,LAL @ LAC,W,32,28,0.533,240,47,...,0.800,8,31,39,28,6,5,15,12,116
3,1610612747,0022300818,2024-02-25,LAL @ PHX,L,31,28,0.525,240,47,...,0.500,3,31,34,28,7,4,10,14,113

In [6]:

# Find team by abbreviation
team_abbreviation = 'DEN'  # Example: Los Angeles Lakers
nba_teams = teams.get_teams()
team_dict = [team for team in nba_teams if team['abbreviation'] == team_abbreviation][0]

# Fetch team game log data
team_id = team_dict['id']
current_season = '2023-24'  # Adjust the season accordingly
game_log = teamgamelog.TeamGameLog(team_id=team_id, season=current_season)

# Convert to DataFrame
game_log_df = game_log.get_data_frames()[0]

# Convert game date to datetime and filter for the last 10 days
game_log_df['GAME_DATE'] = pd.to_datetime(game_log_df['GAME_DATE'])
last_10_days = datetime.now() - timedelta(days=10)
filtered_games_df = game_log_df[game_log_df['GAME_DATE'] > last_10_days]

# Display the filtered DataFrame
filtered_games_df

,Team_ID,Game_ID,GAME_DATE,MATCHUP,WL,W,L,W_PCT,MIN,FGM,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS
0,1610612743,0022300869,2024-03-02,DEN @ LAL,W,42,19,0.689,240,54,...,0.714,11,36,47,34,5,7,10,8,124
1,1610612743,0022300855,2024-02-29,DEN vs. MIA,W,41,19,0.683,240,36,...,0.905,9,32,41,22,10,8,15,23,103
2,1610612743,0022300847,2024-02-28,DEN vs. SAC,W,40,19,0.678,240,46,...,0.909,5,38,43,35,10,6,15,17,117
3,1610612743,0022300824,2024-02-25,DEN @ GSW,W,39,19,0.672,240,43,...,0.846,12,33,45,29,10,5,10,20,119

In [10]:
names = filtered_games_df.columns
print(names)

Index(['Team_ID', 'Game_ID', 'GAME_DATE', 'MATCHUP', 'WL', 'W', 'L', 'W_PCT',
       'MIN', 'FGM', 'FGA', 'FG_PCT', 'FG3M', 'FG3A', 'FG3_PCT', 'FTM', 'FTA',
       'FT_PCT', 'OREB', 'DREB', 'REB', 'AST', 'STL', 'BLK', 'TOV', 'PF',
       'PTS'],
      dtype='object')

In [ ]:
filtered_games_df.rename(columns={'FGM': 'Field_goals_made', 'MIN': 'Minutes', '': 'Minutes'}, inplace=True)